data_insert_player = """
    INSERT INTO player (id, team_id, name) VALUES
        (1, 11, 'Dejounte Murray'),
        (2, 11, 'Trae Young'),
        (3, 11, 'De''Andre Hunter'),
        (4, 11, 'Saddiq Bey'),
        (5, 11, 'John Collins'),
        (6, 2, 'Mikal Bridges'),
        (7, 2, 'Spencer Dinwiddie'),
        (8, 2, 'Royce O''Neale'),
        (9, 2, 'Dorian Finney-Smith'),
        (10, 2, 'Nic Claxton'),
        (11, 1, 'Jayson Tatum'),
        (12, 1, 'Jaylen Brown'),
        (13, 1, 'Marcus Smart'),
        (14, 1, 'Al Horford'),
        (15, 1, 'Derrick White'),
        (16, 12, 'Dennis Smith Jr.'),
        (17, 12, 'P.J. Washington'),
        (18, 12, 'JT Thor'),
        (19, 12, 'Nick Richards'),
        (20, 12, 'Terry Rozier'),
        (21, 6, 'DeMar DeRozan'),
        (22, 6, 'Zach LaVine'),
        (23, 6, 'Nikola Vučević'),
        (24, 6, 'Patrick Williams'),
        (25, 6, 'Patrick Beverley'),
        (26, 7, 'Donovan Mitchell'),
        (27, 7, 'Darius Garland'),
        (28, 7, 'Evan Mobley'),
        (29, 7, 'Jarrett Allen'),
        (30, 7, 'Caris LeVert'),
        (31, 26, 'Reggie Bullock Jr.'),
        (32, 26, 'Tim Hardaway Jr.'),
        (33, 26, 'Christian Wood'),
        (34, 26, 'Luka Dončić'),
        (35, 26, 'Kyrie Irving'),
        (36, 16, 'Nikola Jokić'),
        (37, 16, 'Kentavious Caldwell-Pope'),
        (38, 16, 'Jamal Murray'),
        (39, 16, 'Aaron Gordon'),
        (40, 16, 'Bruce Brown'),
        (41, 8, 'Killian Hayes'),
        (42, 8, 'Jaden Ivey'),
        (43, 8, 'Jalen Duren'),
        (44, 8, 'Cory Joseph'),
        (45, 8, 'Bojan Bogdanović'),
        (46, 21, 'Klay Thompson'),
        (47, 21, 'Draymond Green'),
        (48, 21, 'Jordan Poole'),
        (49, 21, 'Donte DiVincenzo'),
        (50, 21, 'Kevon Looney'),
        (51, 27, 'Kevin Porter Jr.'),
        (52, 27, 'Jalen Green'),
        (53, 27, 'Jabari Smith Jr.'),
        (54, 27, 'Alperen Sengun'),
        (55, 27, 'KJ Martin'),
        (56, 9, 'Buddy Hield'),
        (57, 9, 'Myles Turner'),
        (58, 9, 'Bennedict Mathurin'),
        (59, 9, 'Andrew Nembhard'),
        (60, 9, 'Aaron Nesmith'),
        (61, 22, 'Russell Westbrook'),
        (62, 22, 'Ivica Zubac'),
        (63, 22, 'Eric Gordon'),
        (64, 22, 'Marcus Morris Sr.'),
        (65, 22, 'Norman Powell'),
        (66, 23, 'D''Angelo Russell'),
        (67, 23, 'Dennis Schröder'),
        (68, 23, 'Austin Reaves'),
        (69, 23, 'Malik Beasley'),
        (70, 23, 'Troy Brown Jr.'),
        (71, 28, 'Ja Morant'),
        (72, 28, 'Desmond Bane'),
        (73, 28, 'Dillon Brooks'),
        (74, 28, 'Jaren Jackson Jr.'),
        (75, 28, 'Tyus Jones'),
        (76, 13, 'Tyler Herro'),
        (77, 13, 'Bam Adebayo'),
        (78, 13, 'Jimmy Butler III'),
        (79, 13, 'Caleb Martin'),
        (80, 13, 'Max Strus'),
        (81, 10, 'Jrue Holiday'),
        (82, 10, 'Giannis Antetokounmpo'),
        (83, 10, 'Brook Lopez'),
        (84, 10, 'Grayson Allen'),
        (85, 10, 'Bobby Portis'),
        (86, 17, 'Anthony Edwards'),
        (87, 17, 'Rudy Gobert'),
        (88, 17, 'Jaden McDaniels'),
        (89, 17, 'Mike Conley'),
        (90, 17, 'Kyle Anderson'),
        (91, 29, 'CJ McCollum'),
        (92, 29, 'Trey Murphy III'),
        (93, 29, 'Herbert Jones'),
        (94, 29, 'Jonas Valančiūnas'),
        (95, 29, 'Josh Richardson'),
        (96, 3, 'Julius Randle'),
        (97, 3, 'RJ Barrett'),
        (98, 3, 'Jalen Brunson'),
        (99, 3, 'Josh Hart'),
        (100, 3, 'Quentin Grimes');
    """