data_insert_team = """
    (1, 'Boston Celtics', 1),
    (2, 'Brooklyn Nets', 1),
    (3, 'New York Knicks', 1),
    (4, 'Philadelphia 76ers', 1),
    (5, 'Toronto Raptors', 1),
    (6, 'Chicago Bulls', 2),
    (7, 'Cleveland Cavaliers', 2),
    (8, 'Detroit Pistons', 2),
    (9, 'Indiana Pacers', 2),
    (10, 'Milwaukee Bucks', 2),
    (11, 'Atlanta Hawks', 3),
    (12, 'Charlotte Hornets', 3),
    (13, 'Miami Heat', 3),
    (14, 'Orlando Magic', 3),
    (15, 'Washington Wizards', 3),
    (16, 'Denver Nuggets', 4),
    (17, 'Minnesota Timberwolves', 4),
    (18, 'Oklahoma City Thunder', 4),
    (19, 'Portland Trail Blazers', 4),
    (20, 'Utah Jazz', 4),
    (21, 'Golden State Warriors', 5),
    (22, 'LA Clippers', 5),
    (23, 'Los Angeles Lakers', 5),
    (24, 'Phoenix Suns', 5),
    (25, 'Sacramento Kings', 5),
    (26, 'Dallas Mavericks', 6),
    (27, 'Houston Rockets', 6),
    (28, 'Memphis Grizzlies', 6),
    (29, 'New Orleans Pelicans', 6),
    (30, 'San Antonio Spurs', 6);
"""