data_insert_stadium = """
    INSERT INTO stadium (id, name, city) VALUES
        (1, 'AT&T Center', 'San Antonio'),
        (2, 'American Airlines Center', 'Dallas'),
        (3, 'Ball Arena', 'Denver'),
        (4, 'Barclays Center', 'Brooklyn'),
        (5, 'Capital One Arena', 'Washington'),
        (6, 'Chase Center', 'San Francisco'),
        (7, 'Crypto.com Arena', 'Los Angeles'),
        (9, 'FedExForum', 'Memphis'),
        (10, 'Fiserv Forum', 'Milwaukee'),
        (11, 'Footprint Center', 'Phoenix'),
        (12, 'Gainbridge Fieldhouse', 'Indianapolis'),
        (13, 'Golden 1 Center', 'Sacramento'),
        (14, 'Kaseya Center', 'Miami'),
        (15, 'Kia Center', 'Orlando'),
        (16, 'Little Caesars Arena', 'Detroit'),
        (17, 'Madison Square Garden', 'New York'),
        (18, 'Moda Center', 'Portland'),
        (19, 'Paycom Center', 'Oklahoma City'),
        (20, 'Rocket Mortgage FieldHouse', 'Cleveland'),
        (21, 'Scotiabank Arena', 'Toronto'),
        (22, 'Smoothie King Center', 'New Orleans'),
        (23, 'Spectrum Center', 'Charlotte'),
        (24, 'State Farm Arena', 'Atlanta'),
        (25, 'Target Center', 'Minneapolis'),
        (26, 'TD Garden', 'Boston'),
        (27, 'Toyota Center', 'Houston'),
        (28, 'United Center', 'Chicago'),
        (29, 'Vivint Arena', 'Salt Lake City'),
        (30, 'Wells Fargo Center', 'Philadelphia');
"""